/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.api;

import org.hellosign.openapi.*;
import org.hellosign.openapi.auth.*;
import org.hellosign.openapi.model.*;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BulkSendJobApi
 */
public class BulkSendJobApiTest {

    /**
     * Gets a BulkSendJob that includes all SignatureRequests it has sent.
     *
     * Returns the status of the BulkSendJob and its SignatureRequests specified by the &#x60;bulk_send_job_id&#x60; parameter.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void bulkSendJobGetTest() throws Exception {
        String id = "6e683bc0369ba3d5b6f43c2c22a8031dbf6bd174";
        BulkSendJobGetResponse expected = TestHelper.getFixtureData(BulkSendJobGetResponse.class, "default");
        ApiClient apiClient = TestHelper.setUpMock(200, expected);
        BulkSendJobApi api = new BulkSendJobApi(apiClient);
        BulkSendJobGetResponse actual = api.bulkSendJobGet(id);
        Assert.assertEquals(expected, actual);
    }

    /**
     * Lists the BulkSendJob that you have access to.
     *
     * Returns a list of BulkSendJob that you can access.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void bulkSendJobListTest() throws Exception {
        BulkSendJobListResponse expected = TestHelper.getFixtureData(BulkSendJobListResponse.class, "default");
        ApiClient apiClient = TestHelper.setUpMock(200, expected);
        BulkSendJobApi api = new BulkSendJobApi(apiClient);
        BulkSendJobListResponse actual = api.bulkSendJobList(1, 20);
        Assert.assertEquals(expected, actual);
    }

}
