/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.api;

import org.hellosign.openapi.*;
import org.hellosign.openapi.auth.*;
import org.hellosign.openapi.model.*;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ReportApi
 */
public class ReportApiTest {

    /**
     * Creates one or more report(s).
     *
     * Request the creation of one or more report(s).  When the report(s) have been generated, you will receive an email (one per requested report type) containing a link to download the report as a CSV file. The requested date range may be up to 12 months in duration, and &#x60;start_date&#x60; must not be more than 10 years in the past.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void reportCreateTest() throws Exception {
        ReportCreateRequest request = TestHelper.getFixtureData(ReportCreateRequest.class, "default");
        ReportCreateResponse expected = TestHelper.getFixtureData(ReportCreateResponse.class, "default");
        ApiClient apiClient = TestHelper.setUpMock(200, expected);
        ReportApi api = new ReportApi(apiClient);
        ReportCreateResponse actual = api.reportCreate(request);
        Assert.assertEquals(expected, actual);
    }

}
