/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.hellosign.openapi.model.AccountResponseQuotas;
import org.hellosign.openapi.model.WarningResponse;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AccountResponse
 */
public class AccountResponseTest {
    private final AccountResponse model = new AccountResponse();

    /**
     * Model tests for AccountResponse
     */
    @Test
    public void testAccountResponse() {
        // TODO: test AccountResponse
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'emailAddress'
     */
    @Test
    public void emailAddressTest() {
        // TODO: test emailAddress
    }

    /**
     * Test the property 'isLocked'
     */
    @Test
    public void isLockedTest() {
        // TODO: test isLocked
    }

    /**
     * Test the property 'isPaidHs'
     */
    @Test
    public void isPaidHsTest() {
        // TODO: test isPaidHs
    }

    /**
     * Test the property 'isPaidHf'
     */
    @Test
    public void isPaidHfTest() {
        // TODO: test isPaidHf
    }

    /**
     * Test the property 'quotas'
     */
    @Test
    public void quotasTest() {
        // TODO: test quotas
    }

    /**
     * Test the property 'callbackUrl'
     */
    @Test
    public void callbackUrlTest() {
        // TODO: test callbackUrl
    }

    /**
     * Test the property 'roleCode'
     */
    @Test
    public void roleCodeTest() {
        // TODO: test roleCode
    }

    /**
     * Test the property 'warnings'
     */
    @Test
    public void warningsTest() {
        // TODO: test warnings
    }

}
