/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import org.hellosign.openapi.model.SubOAuth;
import org.hellosign.openapi.model.SubOptions;
import org.hellosign.openapi.model.SubWhiteLabelingOptions;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ApiAppUpdateRequest
 */
public class ApiAppUpdateRequestTest {
    private final ApiAppUpdateRequest model = new ApiAppUpdateRequest();

    /**
     * Model tests for ApiAppUpdateRequest
     */
    @Test
    public void testApiAppUpdateRequest() {
        // TODO: test ApiAppUpdateRequest
    }

    /**
     * Test the property 'callbackUrl'
     */
    @Test
    public void callbackUrlTest() {
        // TODO: test callbackUrl
    }

    /**
     * Test the property 'customLogoFile'
     */
    @Test
    public void customLogoFileTest() {
        // TODO: test customLogoFile
    }

    /**
     * Test the property 'domains'
     */
    @Test
    public void domainsTest() {
        // TODO: test domains
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'oauth'
     */
    @Test
    public void oauthTest() {
        // TODO: test oauth
    }

    /**
     * Test the property 'options'
     */
    @Test
    public void optionsTest() {
        // TODO: test options
    }

    /**
     * Test the property 'whiteLabelingOptions'
     */
    @Test
    public void whiteLabelingOptionsTest() {
        // TODO: test whiteLabelingOptions
    }

}
