/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ApiAppResponseWhiteLabelingOptions
 */
public class ApiAppResponseWhiteLabelingOptionsTest {
    private final ApiAppResponseWhiteLabelingOptions model = new ApiAppResponseWhiteLabelingOptions();

    /**
     * Model tests for ApiAppResponseWhiteLabelingOptions
     */
    @Test
    public void testApiAppResponseWhiteLabelingOptions() {
        // TODO: test ApiAppResponseWhiteLabelingOptions
    }

    /**
     * Test the property 'headerBackgroundColor'
     */
    @Test
    public void headerBackgroundColorTest() {
        // TODO: test headerBackgroundColor
    }

    /**
     * Test the property 'legalVersion'
     */
    @Test
    public void legalVersionTest() {
        // TODO: test legalVersion
    }

    /**
     * Test the property 'linkColor'
     */
    @Test
    public void linkColorTest() {
        // TODO: test linkColor
    }

    /**
     * Test the property 'pageBackgroundColor'
     */
    @Test
    public void pageBackgroundColorTest() {
        // TODO: test pageBackgroundColor
    }

    /**
     * Test the property 'primaryButtonColor'
     */
    @Test
    public void primaryButtonColorTest() {
        // TODO: test primaryButtonColor
    }

    /**
     * Test the property 'primaryButtonColorHover'
     */
    @Test
    public void primaryButtonColorHoverTest() {
        // TODO: test primaryButtonColorHover
    }

    /**
     * Test the property 'primaryButtonTextColor'
     */
    @Test
    public void primaryButtonTextColorTest() {
        // TODO: test primaryButtonTextColor
    }

    /**
     * Test the property 'primaryButtonTextColorHover'
     */
    @Test
    public void primaryButtonTextColorHoverTest() {
        // TODO: test primaryButtonTextColorHover
    }

    /**
     * Test the property 'secondaryButtonColor'
     */
    @Test
    public void secondaryButtonColorTest() {
        // TODO: test secondaryButtonColor
    }

    /**
     * Test the property 'secondaryButtonColorHover'
     */
    @Test
    public void secondaryButtonColorHoverTest() {
        // TODO: test secondaryButtonColorHover
    }

    /**
     * Test the property 'secondaryButtonTextColor'
     */
    @Test
    public void secondaryButtonTextColorTest() {
        // TODO: test secondaryButtonTextColor
    }

    /**
     * Test the property 'secondaryButtonTextColorHover'
     */
    @Test
    public void secondaryButtonTextColorHoverTest() {
        // TODO: test secondaryButtonTextColorHover
    }

    /**
     * Test the property 'textColor1'
     */
    @Test
    public void textColor1Test() {
        // TODO: test textColor1
    }

    /**
     * Test the property 'textColor2'
     */
    @Test
    public void textColor2Test() {
        // TODO: test textColor2
    }

}
