/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.hellosign.openapi.model.ApiAppResponseOAuth;
import org.hellosign.openapi.model.ApiAppResponseOptions;
import org.hellosign.openapi.model.ApiAppResponseOwnerAccount;
import org.hellosign.openapi.model.ApiAppResponseWhiteLabelingOptions;
import org.hellosign.openapi.model.WarningResponse;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ApiAppResponse
 */
public class ApiAppResponseTest {
    private final ApiAppResponse model = new ApiAppResponse();

    /**
     * Model tests for ApiAppResponse
     */
    @Test
    public void testApiAppResponse() {
        // TODO: test ApiAppResponse
    }

    /**
     * Test the property 'callbackUrl'
     */
    @Test
    public void callbackUrlTest() {
        // TODO: test callbackUrl
    }

    /**
     * Test the property 'clientId'
     */
    @Test
    public void clientIdTest() {
        // TODO: test clientId
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'domain'
     */
    @Test
    public void domainTest() {
        // TODO: test domain
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'isApproved'
     */
    @Test
    public void isApprovedTest() {
        // TODO: test isApproved
    }

    /**
     * Test the property 'oauth'
     */
    @Test
    public void oauthTest() {
        // TODO: test oauth
    }

    /**
     * Test the property 'options'
     */
    @Test
    public void optionsTest() {
        // TODO: test options
    }

    /**
     * Test the property 'ownerAccount'
     */
    @Test
    public void ownerAccountTest() {
        // TODO: test ownerAccount
    }

    /**
     * Test the property 'whiteLabelingOptions'
     */
    @Test
    public void whiteLabelingOptionsTest() {
        // TODO: test whiteLabelingOptions
    }

    /**
     * Test the property 'warnings'
     */
    @Test
    public void warningsTest() {
        // TODO: test warnings
    }

}
