/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.hellosign.openapi.model.SubEditorOptions;
import org.hellosign.openapi.model.SubMergeField;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EmbeddedEditUrlRequest
 */
public class EmbeddedEditUrlRequestTest {
    private final EmbeddedEditUrlRequest model = new EmbeddedEditUrlRequest();

    /**
     * Model tests for EmbeddedEditUrlRequest
     */
    @Test
    public void testEmbeddedEditUrlRequest() {
        // TODO: test EmbeddedEditUrlRequest
    }

    /**
     * Test the property 'allowEditCcs'
     */
    @Test
    public void allowEditCcsTest() {
        // TODO: test allowEditCcs
    }

    /**
     * Test the property 'ccRoles'
     */
    @Test
    public void ccRolesTest() {
        // TODO: test ccRoles
    }

    /**
     * Test the property 'editorOptions'
     */
    @Test
    public void editorOptionsTest() {
        // TODO: test editorOptions
    }

    /**
     * Test the property 'forceSignerRoles'
     */
    @Test
    public void forceSignerRolesTest() {
        // TODO: test forceSignerRoles
    }

    /**
     * Test the property 'forceSubjectMessage'
     */
    @Test
    public void forceSubjectMessageTest() {
        // TODO: test forceSubjectMessage
    }

    /**
     * Test the property 'mergeFields'
     */
    @Test
    public void mergeFieldsTest() {
        // TODO: test mergeFields
    }

    /**
     * Test the property 'previewOnly'
     */
    @Test
    public void previewOnlyTest() {
        // TODO: test previewOnly
    }

    /**
     * Test the property 'showPreview'
     */
    @Test
    public void showPreviewTest() {
        // TODO: test showPreview
    }

    /**
     * Test the property 'skipSignerRoles'
     */
    @Test
    public void skipSignerRolesTest() {
        // TODO: test skipSignerRoles
    }

    /**
     * Test the property 'skipSubjectMessage'
     */
    @Test
    public void skipSubjectMessageTest() {
        // TODO: test skipSubjectMessage
    }

    /**
     * Test the property 'testMode'
     */
    @Test
    public void testModeTest() {
        // TODO: test testMode
    }

}
