/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.hellosign.openapi.model.EventCallbackRequestEvent;
import org.hellosign.openapi.model.SignatureRequestResponse;
import org.hellosign.openapi.model.TemplateResponse;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EventCallbackAccountRequestPayload
 */
public class EventCallbackAccountRequestPayloadTest {
    private final EventCallbackAccountRequestPayload model = new EventCallbackAccountRequestPayload();

    /**
     * Model tests for EventCallbackAccountRequestPayload
     */
    @Test
    public void testEventCallbackAccountRequestPayload() {
        // TODO: test EventCallbackAccountRequestPayload
    }

    /**
     * Test the property 'accountGuid'
     */
    @Test
    public void accountGuidTest() {
        // TODO: test accountGuid
    }

    /**
     * Test the property 'clientId'
     */
    @Test
    public void clientIdTest() {
        // TODO: test clientId
    }

    /**
     * Test the property 'event'
     */
    @Test
    public void eventTest() {
        // TODO: test event
    }

    /**
     * Test the property 'signatureRequest'
     */
    @Test
    public void signatureRequestTest() {
        // TODO: test signatureRequest
    }

    /**
     * Test the property 'template'
     */
    @Test
    public void templateTest() {
        // TODO: test template
    }

}
