/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.hellosign.openapi.model.EventCallbackRequestEventMetadata;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EventCallbackRequestEvent
 */
public class EventCallbackRequestEventTest {
    private final EventCallbackRequestEvent model = new EventCallbackRequestEvent();

    /**
     * Model tests for EventCallbackRequestEvent
     */
    @Test
    public void testEventCallbackRequestEvent() {
        // TODO: test EventCallbackRequestEvent
    }

    /**
     * Test the property 'eventTime'
     */
    @Test
    public void eventTimeTest() {
        // TODO: test eventTime
    }

    /**
     * Test the property 'eventType'
     */
    @Test
    public void eventTypeTest() {
        // TODO: test eventType
    }

    /**
     * Test the property 'eventHash'
     */
    @Test
    public void eventHashTest() {
        // TODO: test eventHash
    }

    /**
     * Test the property 'eventMetadata'
     */
    @Test
    public void eventMetadataTest() {
        // TODO: test eventMetadata
    }

}
