/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EventCallbackRequestEventMetadata
 */
public class EventCallbackRequestEventMetadataTest {
    private final EventCallbackRequestEventMetadata model = new EventCallbackRequestEventMetadata();

    /**
     * Model tests for EventCallbackRequestEventMetadata
     */
    @Test
    public void testEventCallbackRequestEventMetadata() {
        // TODO: test EventCallbackRequestEventMetadata
    }

    /**
     * Test the property 'relatedSignatureId'
     */
    @Test
    public void relatedSignatureIdTest() {
        // TODO: test relatedSignatureId
    }

    /**
     * Test the property 'reportedForAccountId'
     */
    @Test
    public void reportedForAccountIdTest() {
        // TODO: test reportedForAccountId
    }

    /**
     * Test the property 'reportedForAppId'
     */
    @Test
    public void reportedForAppIdTest() {
        // TODO: test reportedForAppId
    }

    /**
     * Test the property 'eventMessage'
     */
    @Test
    public void eventMessageTest() {
        // TODO: test eventMessage
    }

}
