/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ListInfoResponse
 */
public class ListInfoResponseTest {
    private final ListInfoResponse model = new ListInfoResponse();

    /**
     * Model tests for ListInfoResponse
     */
    @Test
    public void testListInfoResponse() {
        // TODO: test ListInfoResponse
    }

    /**
     * Test the property 'numPages'
     */
    @Test
    public void numPagesTest() {
        // TODO: test numPages
    }

    /**
     * Test the property 'numResponse'
     */
    @Test
    public void numResponseTest() {
        // TODO: test numResponse
    }

    /**
     * Test the property 'numResults'
     */
    @Test
    public void numResultsTest() {
        // TODO: test numResults
    }

    /**
     * Test the property 'page'
     */
    @Test
    public void pageTest() {
        // TODO: test page
    }

    /**
     * Test the property 'pageSize'
     */
    @Test
    public void pageSizeTest() {
        // TODO: test pageSize
    }

}
