/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SignatureRequestResponseSignatures
 */
public class SignatureRequestResponseSignaturesTest {
    private final SignatureRequestResponseSignatures model = new SignatureRequestResponseSignatures();

    /**
     * Model tests for SignatureRequestResponseSignatures
     */
    @Test
    public void testSignatureRequestResponseSignatures() {
        // TODO: test SignatureRequestResponseSignatures
    }

    /**
     * Test the property 'signatureId'
     */
    @Test
    public void signatureIdTest() {
        // TODO: test signatureId
    }

    /**
     * Test the property 'signerEmailAddress'
     */
    @Test
    public void signerEmailAddressTest() {
        // TODO: test signerEmailAddress
    }

    /**
     * Test the property 'signerName'
     */
    @Test
    public void signerNameTest() {
        // TODO: test signerName
    }

    /**
     * Test the property 'signerRole'
     */
    @Test
    public void signerRoleTest() {
        // TODO: test signerRole
    }

    /**
     * Test the property 'order'
     */
    @Test
    public void orderTest() {
        // TODO: test order
    }

    /**
     * Test the property 'statusCode'
     */
    @Test
    public void statusCodeTest() {
        // TODO: test statusCode
    }

    /**
     * Test the property 'declineReason'
     */
    @Test
    public void declineReasonTest() {
        // TODO: test declineReason
    }

    /**
     * Test the property 'signedAt'
     */
    @Test
    public void signedAtTest() {
        // TODO: test signedAt
    }

    /**
     * Test the property 'lastViewedAt'
     */
    @Test
    public void lastViewedAtTest() {
        // TODO: test lastViewedAt
    }

    /**
     * Test the property 'lastRemindedAt'
     */
    @Test
    public void lastRemindedAtTest() {
        // TODO: test lastRemindedAt
    }

    /**
     * Test the property 'hasPin'
     */
    @Test
    public void hasPinTest() {
        // TODO: test hasPin
    }

    /**
     * Test the property 'hasSmsAuth'
     */
    @Test
    public void hasSmsAuthTest() {
        // TODO: test hasSmsAuth
    }

    /**
     * Test the property 'reassignedBy'
     */
    @Test
    public void reassignedByTest() {
        // TODO: test reassignedBy
    }

    /**
     * Test the property 'reassignmentReason'
     */
    @Test
    public void reassignmentReasonTest() {
        // TODO: test reassignmentReason
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

}
