/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.hellosign.openapi.model.SubAttachment;
import org.hellosign.openapi.model.SubCustomField;
import org.hellosign.openapi.model.SubFieldOptions;
import org.hellosign.openapi.model.SubFormFieldGroup;
import org.hellosign.openapi.model.SubFormFieldRule;
import org.hellosign.openapi.model.SubFormFieldsPerDocumentBase;
import org.hellosign.openapi.model.SubSignatureRequestEmbeddedSigner;
import org.hellosign.openapi.model.SubSigningOptions;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SignatureRequestCreateEmbeddedRequest
 */
public class SignatureRequestCreateEmbeddedRequestTest {
    private final SignatureRequestCreateEmbeddedRequest model = new SignatureRequestCreateEmbeddedRequest();

    /**
     * Model tests for SignatureRequestCreateEmbeddedRequest
     */
    @Test
    public void testSignatureRequestCreateEmbeddedRequest() {
        // TODO: test SignatureRequestCreateEmbeddedRequest
    }

    /**
     * Test the property 'file'
     */
    @Test
    public void fileTest() {
        // TODO: test file
    }

    /**
     * Test the property 'fileUrl'
     */
    @Test
    public void fileUrlTest() {
        // TODO: test fileUrl
    }

    /**
     * Test the property 'allowDecline'
     */
    @Test
    public void allowDeclineTest() {
        // TODO: test allowDecline
    }

    /**
     * Test the property 'allowReassign'
     */
    @Test
    public void allowReassignTest() {
        // TODO: test allowReassign
    }

    /**
     * Test the property 'attachments'
     */
    @Test
    public void attachmentsTest() {
        // TODO: test attachments
    }

    /**
     * Test the property 'ccEmailAddresses'
     */
    @Test
    public void ccEmailAddressesTest() {
        // TODO: test ccEmailAddresses
    }

    /**
     * Test the property 'clientId'
     */
    @Test
    public void clientIdTest() {
        // TODO: test clientId
    }

    /**
     * Test the property 'customFields'
     */
    @Test
    public void customFieldsTest() {
        // TODO: test customFields
    }

    /**
     * Test the property 'fieldOptions'
     */
    @Test
    public void fieldOptionsTest() {
        // TODO: test fieldOptions
    }

    /**
     * Test the property 'formFieldGroups'
     */
    @Test
    public void formFieldGroupsTest() {
        // TODO: test formFieldGroups
    }

    /**
     * Test the property 'formFieldRules'
     */
    @Test
    public void formFieldRulesTest() {
        // TODO: test formFieldRules
    }

    /**
     * Test the property 'formFieldsPerDocument'
     */
    @Test
    public void formFieldsPerDocumentTest() {
        // TODO: test formFieldsPerDocument
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'signers'
     */
    @Test
    public void signersTest() {
        // TODO: test signers
    }

    /**
     * Test the property 'signingOptions'
     */
    @Test
    public void signingOptionsTest() {
        // TODO: test signingOptions
    }

    /**
     * Test the property 'subject'
     */
    @Test
    public void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'testMode'
     */
    @Test
    public void testModeTest() {
        // TODO: test testMode
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'useTextTags'
     */
    @Test
    public void useTextTagsTest() {
        // TODO: test useTextTags
    }

}
