/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.hellosign.openapi.model.SubBulkSignerList;
import org.hellosign.openapi.model.SubCC;
import org.hellosign.openapi.model.SubCustomField;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SignatureRequestBulkSendWithTemplateRequest
 */
public class SignatureRequestBulkSendWithTemplateRequestTest {
    private final SignatureRequestBulkSendWithTemplateRequest model = new SignatureRequestBulkSendWithTemplateRequest();

    /**
     * Model tests for SignatureRequestBulkSendWithTemplateRequest
     */
    @Test
    public void testSignatureRequestBulkSendWithTemplateRequest() {
        // TODO: test SignatureRequestBulkSendWithTemplateRequest
    }

    /**
     * Test the property 'templateIds'
     */
    @Test
    public void templateIdsTest() {
        // TODO: test templateIds
    }

    /**
     * Test the property 'signerFile'
     */
    @Test
    public void signerFileTest() {
        // TODO: test signerFile
    }

    /**
     * Test the property 'signerList'
     */
    @Test
    public void signerListTest() {
        // TODO: test signerList
    }

    /**
     * Test the property 'allowDecline'
     */
    @Test
    public void allowDeclineTest() {
        // TODO: test allowDecline
    }

    /**
     * Test the property 'ccs'
     */
    @Test
    public void ccsTest() {
        // TODO: test ccs
    }

    /**
     * Test the property 'customFields'
     */
    @Test
    public void customFieldsTest() {
        // TODO: test customFields
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'signingRedirectUrl'
     */
    @Test
    public void signingRedirectUrlTest() {
        // TODO: test signingRedirectUrl
    }

    /**
     * Test the property 'subject'
     */
    @Test
    public void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'testMode'
     */
    @Test
    public void testModeTest() {
        // TODO: test testMode
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

}
