/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.hellosign.openapi.model.SignatureRequestResponseCustomField;
import org.hellosign.openapi.model.SignatureRequestResponseData;
import org.hellosign.openapi.model.SignatureRequestResponseSignatures;
import org.hellosign.openapi.model.WarningResponse;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SignatureRequestResponse
 */
public class SignatureRequestResponseTest {
    private final SignatureRequestResponse model = new SignatureRequestResponse();

    /**
     * Model tests for SignatureRequestResponse
     */
    @Test
    public void testSignatureRequestResponse() {
        // TODO: test SignatureRequestResponse
    }

    /**
     * Test the property 'testMode'
     */
    @Test
    public void testModeTest() {
        // TODO: test testMode
    }

    /**
     * Test the property 'signatureRequestId'
     */
    @Test
    public void signatureRequestIdTest() {
        // TODO: test signatureRequestId
    }

    /**
     * Test the property 'requesterEmailAddress'
     */
    @Test
    public void requesterEmailAddressTest() {
        // TODO: test requesterEmailAddress
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'originalTitle'
     */
    @Test
    public void originalTitleTest() {
        // TODO: test originalTitle
    }

    /**
     * Test the property 'subject'
     */
    @Test
    public void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'isComplete'
     */
    @Test
    public void isCompleteTest() {
        // TODO: test isComplete
    }

    /**
     * Test the property 'isDeclined'
     */
    @Test
    public void isDeclinedTest() {
        // TODO: test isDeclined
    }

    /**
     * Test the property 'hasError'
     */
    @Test
    public void hasErrorTest() {
        // TODO: test hasError
    }

    /**
     * Test the property 'finalCopyUri'
     */
    @Test
    public void finalCopyUriTest() {
        // TODO: test finalCopyUri
    }

    /**
     * Test the property 'filesUrl'
     */
    @Test
    public void filesUrlTest() {
        // TODO: test filesUrl
    }

    /**
     * Test the property 'signingUrl'
     */
    @Test
    public void signingUrlTest() {
        // TODO: test signingUrl
    }

    /**
     * Test the property 'detailsUrl'
     */
    @Test
    public void detailsUrlTest() {
        // TODO: test detailsUrl
    }

    /**
     * Test the property 'ccEmailAddresses'
     */
    @Test
    public void ccEmailAddressesTest() {
        // TODO: test ccEmailAddresses
    }

    /**
     * Test the property 'signingRedirectUrl'
     */
    @Test
    public void signingRedirectUrlTest() {
        // TODO: test signingRedirectUrl
    }

    /**
     * Test the property 'customFields'
     */
    @Test
    public void customFieldsTest() {
        // TODO: test customFields
    }

    /**
     * Test the property 'responseData'
     */
    @Test
    public void responseDataTest() {
        // TODO: test responseData
    }

    /**
     * Test the property 'signatures'
     */
    @Test
    public void signaturesTest() {
        // TODO: test signatures
    }

    /**
     * Test the property 'warnings'
     */
    @Test
    public void warningsTest() {
        // TODO: test warnings
    }

}
