/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.hellosign.openapi.model.SignatureRequestResponse;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SignatureRequestGetResponse
 */
public class SignatureRequestGetResponseTest {
    private final SignatureRequestGetResponse model = new SignatureRequestGetResponse();

    /**
     * Model tests for SignatureRequestGetResponse
     */
    @Test
    public void testSignatureRequestGetResponse() {
        // TODO: test SignatureRequestGetResponse
    }

    /**
     * Test the property 'signatureRequest'
     */
    @Test
    public void signatureRequestTest() {
        // TODO: test signatureRequest
    }

}
