/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SubEditorOptions
 */
public class SubEditorOptionsTest {
    private final SubEditorOptions model = new SubEditorOptions();

    /**
     * Model tests for SubEditorOptions
     */
    @Test
    public void testSubEditorOptions() {
        // TODO: test SubEditorOptions
    }

    /**
     * Test the property 'allowEditSigners'
     */
    @Test
    public void allowEditSignersTest() {
        // TODO: test allowEditSigners
    }

    /**
     * Test the property 'allowEditDocuments'
     */
    @Test
    public void allowEditDocumentsTest() {
        // TODO: test allowEditDocuments
    }

}
