/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SubFormFieldsPerDocumentTypeEnum
 */
public class SubFormFieldsPerDocumentTypeEnumTest {
    /**
     * Model tests for SubFormFieldsPerDocumentTypeEnum
     */
    @Test
    public void testSubFormFieldsPerDocumentTypeEnum() {
        // TODO: test SubFormFieldsPerDocumentTypeEnum
    }

}
