/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.hellosign.openapi.model.SubFormFieldsPerDocumentCheckbox;
import org.hellosign.openapi.model.SubFormFieldsPerDocumentCheckboxMerge;
import org.hellosign.openapi.model.SubFormFieldsPerDocumentDateSigned;
import org.hellosign.openapi.model.SubFormFieldsPerDocumentDropdown;
import org.hellosign.openapi.model.SubFormFieldsPerDocumentHyperlink;
import org.hellosign.openapi.model.SubFormFieldsPerDocumentInitials;
import org.hellosign.openapi.model.SubFormFieldsPerDocumentRadio;
import org.hellosign.openapi.model.SubFormFieldsPerDocumentSignature;
import org.hellosign.openapi.model.SubFormFieldsPerDocumentText;
import org.hellosign.openapi.model.SubFormFieldsPerDocumentTextMerge;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SubFormFieldsPerDocumentBase
 */
public class SubFormFieldsPerDocumentBaseTest {
    private final SubFormFieldsPerDocumentBase model = new SubFormFieldsPerDocumentBase();

    /**
     * Model tests for SubFormFieldsPerDocumentBase
     */
    @Test
    public void testSubFormFieldsPerDocumentBase() {
        // TODO: test SubFormFieldsPerDocumentBase
    }

    /**
     * Test the property 'apiId'
     */
    @Test
    public void apiIdTest() {
        // TODO: test apiId
    }

    /**
     * Test the property 'height'
     */
    @Test
    public void heightTest() {
        // TODO: test height
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'page'
     */
    @Test
    public void pageTest() {
        // TODO: test page
    }

    /**
     * Test the property 'required'
     */
    @Test
    public void requiredTest() {
        // TODO: test required
    }

    /**
     * Test the property 'signer'
     */
    @Test
    public void signerTest() {
        // TODO: test signer
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'width'
     */
    @Test
    public void widthTest() {
        // TODO: test width
    }

    /**
     * Test the property 'x'
     */
    @Test
    public void xTest() {
        // TODO: test x
    }

    /**
     * Test the property 'y'
     */
    @Test
    public void yTest() {
        // TODO: test y
    }

}
