/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SubFormFieldGroup
 */
public class SubFormFieldGroupTest {
    private final SubFormFieldGroup model = new SubFormFieldGroup();

    /**
     * Model tests for SubFormFieldGroup
     */
    @Test
    public void testSubFormFieldGroup() {
        // TODO: test SubFormFieldGroup
    }

    /**
     * Test the property 'groupId'
     */
    @Test
    public void groupIdTest() {
        // TODO: test groupId
    }

    /**
     * Test the property 'groupLabel'
     */
    @Test
    public void groupLabelTest() {
        // TODO: test groupLabel
    }

    /**
     * Test the property 'requirement'
     */
    @Test
    public void requirementTest() {
        // TODO: test requirement
    }

}
