/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.hellosign.openapi.model.SubFormFieldRuleAction;
import org.hellosign.openapi.model.SubFormFieldRuleTrigger;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SubFormFieldRule
 */
public class SubFormFieldRuleTest {
    private final SubFormFieldRule model = new SubFormFieldRule();

    /**
     * Model tests for SubFormFieldRule
     */
    @Test
    public void testSubFormFieldRule() {
        // TODO: test SubFormFieldRule
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'triggerOperator'
     */
    @Test
    public void triggerOperatorTest() {
        // TODO: test triggerOperator
    }

    /**
     * Test the property 'triggers'
     */
    @Test
    public void triggersTest() {
        // TODO: test triggers
    }

    /**
     * Test the property 'actions'
     */
    @Test
    public void actionsTest() {
        // TODO: test actions
    }

}
