/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SubOptions
 */
public class SubOptionsTest {
    private final SubOptions model = new SubOptions();

    /**
     * Model tests for SubOptions
     */
    @Test
    public void testSubOptions() {
        // TODO: test SubOptions
    }

    /**
     * Test the property 'canInsertEverywhere'
     */
    @Test
    public void canInsertEverywhereTest() {
        // TODO: test canInsertEverywhere
    }

}
