/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SubSignatureRequestEmbeddedTemplateSigner
 */
public class SubSignatureRequestEmbeddedTemplateSignerTest {
    private final SubSignatureRequestEmbeddedTemplateSigner model = new SubSignatureRequestEmbeddedTemplateSigner();

    /**
     * Model tests for SubSignatureRequestEmbeddedTemplateSigner
     */
    @Test
    public void testSubSignatureRequestEmbeddedTemplateSigner() {
        // TODO: test SubSignatureRequestEmbeddedTemplateSigner
    }

    /**
     * Test the property 'role'
     */
    @Test
    public void roleTest() {
        // TODO: test role
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'emailAddress'
     */
    @Test
    public void emailAddressTest() {
        // TODO: test emailAddress
    }

    /**
     * Test the property 'pin'
     */
    @Test
    public void pinTest() {
        // TODO: test pin
    }

    /**
     * Test the property 'smsPhoneNumber'
     */
    @Test
    public void smsPhoneNumberTest() {
        // TODO: test smsPhoneNumber
    }

}
