/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SubSigningOptions
 */
public class SubSigningOptionsTest {
    private final SubSigningOptions model = new SubSigningOptions();

    /**
     * Model tests for SubSigningOptions
     */
    @Test
    public void testSubSigningOptions() {
        // TODO: test SubSigningOptions
    }

    /**
     * Test the property 'defaultType'
     */
    @Test
    public void defaultTypeTest() {
        // TODO: test defaultType
    }

    /**
     * Test the property 'draw'
     */
    @Test
    public void drawTest() {
        // TODO: test draw
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'upload'
     */
    @Test
    public void uploadTest() {
        // TODO: test upload
    }

}
