/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.hellosign.openapi.model.TemplateResponseDocumentCustomFieldAvgTextLength;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TemplateResponseDocumentCustomField
 */
public class TemplateResponseDocumentCustomFieldTest {
    private final TemplateResponseDocumentCustomField model = new TemplateResponseDocumentCustomField();

    /**
     * Model tests for TemplateResponseDocumentCustomField
     */
    @Test
    public void testTemplateResponseDocumentCustomField() {
        // TODO: test TemplateResponseDocumentCustomField
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'x'
     */
    @Test
    public void xTest() {
        // TODO: test x
    }

    /**
     * Test the property 'y'
     */
    @Test
    public void yTest() {
        // TODO: test y
    }

    /**
     * Test the property 'width'
     */
    @Test
    public void widthTest() {
        // TODO: test width
    }

    /**
     * Test the property 'height'
     */
    @Test
    public void heightTest() {
        // TODO: test height
    }

    /**
     * Test the property 'required'
     */
    @Test
    public void requiredTest() {
        // TODO: test required
    }

    /**
     * Test the property 'group'
     */
    @Test
    public void groupTest() {
        // TODO: test group
    }

    /**
     * Test the property 'avgTextLength'
     */
    @Test
    public void avgTextLengthTest() {
        // TODO: test avgTextLength
    }

    /**
     * Test the property 'namedFormFields'
     */
    @Test
    public void namedFormFieldsTest() {
        // TODO: test namedFormFields
    }

    /**
     * Test the property 'reusableFormId'
     */
    @Test
    public void reusableFormIdTest() {
        // TODO: test reusableFormId
    }

}
