/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TemplateResponseAccountQuota
 */
public class TemplateResponseAccountQuotaTest {
    private final TemplateResponseAccountQuota model = new TemplateResponseAccountQuota();

    /**
     * Model tests for TemplateResponseAccountQuota
     */
    @Test
    public void testTemplateResponseAccountQuota() {
        // TODO: test TemplateResponseAccountQuota
    }

    /**
     * Test the property 'templatesLeft'
     */
    @Test
    public void templatesLeftTest() {
        // TODO: test templatesLeft
    }

    /**
     * Test the property 'apiSignatureRequestsLeft'
     */
    @Test
    public void apiSignatureRequestsLeftTest() {
        // TODO: test apiSignatureRequestsLeft
    }

    /**
     * Test the property 'documentsLeft'
     */
    @Test
    public void documentsLeftTest() {
        // TODO: test documentsLeft
    }

}
