/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TemplateResponseDocumentCustomFieldAvgTextLength
 */
public class TemplateResponseDocumentCustomFieldAvgTextLengthTest {
    private final TemplateResponseDocumentCustomFieldAvgTextLength model = new TemplateResponseDocumentCustomFieldAvgTextLength();

    /**
     * Model tests for TemplateResponseDocumentCustomFieldAvgTextLength
     */
    @Test
    public void testTemplateResponseDocumentCustomFieldAvgTextLength() {
        // TODO: test TemplateResponseDocumentCustomFieldAvgTextLength
    }

    /**
     * Test the property 'numLines'
     */
    @Test
    public void numLinesTest() {
        // TODO: test numLines
    }

    /**
     * Test the property 'numCharsPerLine'
     */
    @Test
    public void numCharsPerLineTest() {
        // TODO: test numCharsPerLine
    }

}
