/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.hellosign.openapi.model.TemplateResponseDocumentCustomField;
import org.hellosign.openapi.model.TemplateResponseDocumentFieldGroup;
import org.hellosign.openapi.model.TemplateResponseDocumentFormField;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TemplateResponseDocument
 */
public class TemplateResponseDocumentTest {
    private final TemplateResponseDocument model = new TemplateResponseDocument();

    /**
     * Model tests for TemplateResponseDocument
     */
    @Test
    public void testTemplateResponseDocument() {
        // TODO: test TemplateResponseDocument
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'index'
     */
    @Test
    public void indexTest() {
        // TODO: test index
    }

    /**
     * Test the property 'fieldGroups'
     */
    @Test
    public void fieldGroupsTest() {
        // TODO: test fieldGroups
    }

    /**
     * Test the property 'formFields'
     */
    @Test
    public void formFieldsTest() {
        // TODO: test formFields
    }

    /**
     * Test the property 'customFields'
     */
    @Test
    public void customFieldsTest() {
        // TODO: test customFields
    }

}
