/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.hellosign.openapi.model.SubEditorOptions;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UnclaimedDraftEditAndResendRequest
 */
public class UnclaimedDraftEditAndResendRequestTest {
    private final UnclaimedDraftEditAndResendRequest model = new UnclaimedDraftEditAndResendRequest();

    /**
     * Model tests for UnclaimedDraftEditAndResendRequest
     */
    @Test
    public void testUnclaimedDraftEditAndResendRequest() {
        // TODO: test UnclaimedDraftEditAndResendRequest
    }

    /**
     * Test the property 'clientId'
     */
    @Test
    public void clientIdTest() {
        // TODO: test clientId
    }

    /**
     * Test the property 'editorOptions'
     */
    @Test
    public void editorOptionsTest() {
        // TODO: test editorOptions
    }

    /**
     * Test the property 'isForEmbeddedSigning'
     */
    @Test
    public void isForEmbeddedSigningTest() {
        // TODO: test isForEmbeddedSigning
    }

    /**
     * Test the property 'requesterEmailAddress'
     */
    @Test
    public void requesterEmailAddressTest() {
        // TODO: test requesterEmailAddress
    }

    /**
     * Test the property 'requestingRedirectUrl'
     */
    @Test
    public void requestingRedirectUrlTest() {
        // TODO: test requestingRedirectUrl
    }

    /**
     * Test the property 'signingRedirectUrl'
     */
    @Test
    public void signingRedirectUrlTest() {
        // TODO: test signingRedirectUrl
    }

    /**
     * Test the property 'testMode'
     */
    @Test
    public void testModeTest() {
        // TODO: test testMode
    }

}
