/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.hellosign.openapi.model.SubCC;
import org.hellosign.openapi.model.SubCustomField;
import org.hellosign.openapi.model.SubEditorOptions;
import org.hellosign.openapi.model.SubFieldOptions;
import org.hellosign.openapi.model.SubSigningOptions;
import org.hellosign.openapi.model.SubUnclaimedDraftEmbeddedTemplateSigner;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UnclaimedDraftCreateEmbeddedWithTemplateRequest
 */
public class UnclaimedDraftCreateEmbeddedWithTemplateRequestTest {
    private final UnclaimedDraftCreateEmbeddedWithTemplateRequest model = new UnclaimedDraftCreateEmbeddedWithTemplateRequest();

    /**
     * Model tests for UnclaimedDraftCreateEmbeddedWithTemplateRequest
     */
    @Test
    public void testUnclaimedDraftCreateEmbeddedWithTemplateRequest() {
        // TODO: test UnclaimedDraftCreateEmbeddedWithTemplateRequest
    }

    /**
     * Test the property 'allowDecline'
     */
    @Test
    public void allowDeclineTest() {
        // TODO: test allowDecline
    }

    /**
     * Test the property 'allowReassign'
     */
    @Test
    public void allowReassignTest() {
        // TODO: test allowReassign
    }

    /**
     * Test the property 'ccs'
     */
    @Test
    public void ccsTest() {
        // TODO: test ccs
    }

    /**
     * Test the property 'clientId'
     */
    @Test
    public void clientIdTest() {
        // TODO: test clientId
    }

    /**
     * Test the property 'customFields'
     */
    @Test
    public void customFieldsTest() {
        // TODO: test customFields
    }

    /**
     * Test the property 'editorOptions'
     */
    @Test
    public void editorOptionsTest() {
        // TODO: test editorOptions
    }

    /**
     * Test the property 'fieldOptions'
     */
    @Test
    public void fieldOptionsTest() {
        // TODO: test fieldOptions
    }

    /**
     * Test the property 'file'
     */
    @Test
    public void fileTest() {
        // TODO: test file
    }

    /**
     * Test the property 'fileUrl'
     */
    @Test
    public void fileUrlTest() {
        // TODO: test fileUrl
    }

    /**
     * Test the property 'holdRequest'
     */
    @Test
    public void holdRequestTest() {
        // TODO: test holdRequest
    }

    /**
     * Test the property 'isForEmbeddedSigning'
     */
    @Test
    public void isForEmbeddedSigningTest() {
        // TODO: test isForEmbeddedSigning
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'previewOnly'
     */
    @Test
    public void previewOnlyTest() {
        // TODO: test previewOnly
    }

    /**
     * Test the property 'requesterEmailAddress'
     */
    @Test
    public void requesterEmailAddressTest() {
        // TODO: test requesterEmailAddress
    }

    /**
     * Test the property 'requestingRedirectUrl'
     */
    @Test
    public void requestingRedirectUrlTest() {
        // TODO: test requestingRedirectUrl
    }

    /**
     * Test the property 'showPreview'
     */
    @Test
    public void showPreviewTest() {
        // TODO: test showPreview
    }

    /**
     * Test the property 'signers'
     */
    @Test
    public void signersTest() {
        // TODO: test signers
    }

    /**
     * Test the property 'signingOptions'
     */
    @Test
    public void signingOptionsTest() {
        // TODO: test signingOptions
    }

    /**
     * Test the property 'signingRedirectUrl'
     */
    @Test
    public void signingRedirectUrlTest() {
        // TODO: test signingRedirectUrl
    }

    /**
     * Test the property 'skipMeNow'
     */
    @Test
    public void skipMeNowTest() {
        // TODO: test skipMeNow
    }

    /**
     * Test the property 'subject'
     */
    @Test
    public void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'templateIds'
     */
    @Test
    public void templateIdsTest() {
        // TODO: test templateIds
    }

    /**
     * Test the property 'testMode'
     */
    @Test
    public void testModeTest() {
        // TODO: test testMode
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

}
