/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.hellosign.openapi.model.UnclaimedDraftResponse;
import org.hellosign.openapi.model.WarningResponse;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UnclaimedDraftCreateResponse
 */
public class UnclaimedDraftCreateResponseTest {
    private final UnclaimedDraftCreateResponse model = new UnclaimedDraftCreateResponse();

    /**
     * Model tests for UnclaimedDraftCreateResponse
     */
    @Test
    public void testUnclaimedDraftCreateResponse() {
        // TODO: test UnclaimedDraftCreateResponse
    }

    /**
     * Test the property 'unclaimedDraft'
     */
    @Test
    public void unclaimedDraftTest() {
        // TODO: test unclaimedDraft
    }

    /**
     * Test the property 'warnings'
     */
    @Test
    public void warningsTest() {
        // TODO: test warnings
    }

}
