/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.hellosign.openapi.model.WarningResponse;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UnclaimedDraftResponse
 */
public class UnclaimedDraftResponseTest {
    private final UnclaimedDraftResponse model = new UnclaimedDraftResponse();

    /**
     * Model tests for UnclaimedDraftResponse
     */
    @Test
    public void testUnclaimedDraftResponse() {
        // TODO: test UnclaimedDraftResponse
    }

    /**
     * Test the property 'signatureRequestId'
     */
    @Test
    public void signatureRequestIdTest() {
        // TODO: test signatureRequestId
    }

    /**
     * Test the property 'claimUrl'
     */
    @Test
    public void claimUrlTest() {
        // TODO: test claimUrl
    }

    /**
     * Test the property 'signingRedirectUrl'
     */
    @Test
    public void signingRedirectUrlTest() {
        // TODO: test signingRedirectUrl
    }

    /**
     * Test the property 'requestingRedirectUrl'
     */
    @Test
    public void requestingRedirectUrlTest() {
        // TODO: test requestingRedirectUrl
    }

    /**
     * Test the property 'expiresAt'
     */
    @Test
    public void expiresAtTest() {
        // TODO: test expiresAt
    }

    /**
     * Test the property 'testMode'
     */
    @Test
    public void testModeTest() {
        // TODO: test testMode
    }

    /**
     * Test the property 'warnings'
     */
    @Test
    public void warningsTest() {
        // TODO: test warnings
    }

}
