/*
 * HelloSign API
 * HelloSign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hellosign.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for WarningResponse
 */
public class WarningResponseTest {
    private final WarningResponse model = new WarningResponse();

    /**
     * Model tests for WarningResponse
     */
    @Test
    public void testWarningResponse() {
        // TODO: test WarningResponse
    }

    /**
     * Test the property 'warningMsg'
     */
    @Test
    public void warningMsgTest() {
        // TODO: test warningMsg
    }

    /**
     * Test the property 'warningName'
     */
    @Test
    public void warningNameTest() {
        // TODO: test warningName
    }

}
